/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.timer[_ngcontent-%COMP%]{\r\n    text-align: center;\r\n    font-family: sans-serif;\r\n    font-weight: 100;\r\n    padding-top: 15px;\r\n    padding-bottom: 15px;\r\n}\r\n\r\nh1[_ngcontent-%COMP%]{\r\n  font-weight: 100;\r\n  font-size: 40px;\r\n  margin: 40px 0px 20px;\r\n}\r\n\r\n#clockdiv[_ngcontent-%COMP%]{\r\n	font-family: sans-serif;\r\n	color: #FFFFFF;\r\n	display: inline-block;\r\n	font-weight: 100;\r\n	text-align: center;\r\n	font-size: 30px;\r\n}\r\n\r\n#clockdiv[_ngcontent-%COMP%]    > div[_ngcontent-%COMP%]{\r\n	padding: 10px;\r\n	border-radius: 3px;\r\n	background: #000000;\r\n	display: inline-block;\r\n}\r\n\r\n#clockdiv[_ngcontent-%COMP%]   div[_ngcontent-%COMP%]    > span[_ngcontent-%COMP%]{\r\n	padding: 15px;\r\n	border-radius: 3px;\r\n	background: #0e0e0e;\r\n	display: inline-block;\r\n}\r\n\r\n.smalltext[_ngcontent-%COMP%]{\r\n	padding-top: 5px;\r\n	font-size: 16px;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovbXRiL3NyYy9hcHAvaG9tZS9vdXItdGFncy9vdXItdGFncy5jb21wb25lbnQuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Y6L210Yi9zcmMvYXBwL2hvbWUvb3VyLXRhZ3Mvb3VyLXRhZ3MuY29tcG9uZW50LmNzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
