/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.cont[_ngcontent-%COMP%]{\r\n    border-style: solid;\r\n    border-color: #888888;\r\n    border-radius: 4px;\r\n    border-width: 1px;\r\n    padding: 15px;\r\n    box-shadow: 5px 5px 2px #888888;\r\n}\r\n\r\n.gallery-headding[_ngcontent-%COMP%]{\r\n    align:center;\r\n    text-align: center;\r\n    float: center;\r\n}\r\n.gallery-footer[_ngcontent-%COMP%]{\r\n    margin-top: 10px;\r\n    border-top-style: solid;\r\n    border-top-width: 1px;\r\n    border-top-color: #888888;\r\n\r\n    border-left-style: solid;\r\n    border-left-color: #888888;\r\n    border-left-width: 5px;\r\n\r\n    padding: 0px 0px 5px 10px;\r\n}\r\n\r\n.gallery-footer[_ngcontent-%COMP%]   h1[_ngcontent-%COMP%]{\r\n    color: black;\r\n    font-weight: bold;\r\n}\r\n\r\n\r\n.imgcontainer[_ngcontent-%COMP%]{\r\n    padding-bottom: 15px;\r\n    border-radius: 10px;\r\n}\r\n\r\nimg[_ngcontent-%COMP%]{\r\n    box-shadow: 2px 1px 1px #888888;\r\n    transition: .3s transform;\r\n    transform: translateZ(0);\r\n    border-radius: 10px;\r\n}\r\n\r\nimg[_ngcontent-%COMP%]:hover {\r\n  z-index: 1;\r\n  transform: scale(1.05,1.05);\r\n  transition: .5s transform;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovbXRiL3NyYy9hcHAvZ2FsbGVyeS9nYWxsZXJ5LmNvbXBvbmVudC5jc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRjovbXRiL3NyYy9hcHAvZ2FsbGVyeS9nYWxsZXJ5LmNvbXBvbmVudC5jc3MiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
