/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './our-team.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../../../../../src/app/home/our-team/our-team.component';
const styles_OurTeamComponent:any[] = [i0.styles];
export const RenderType_OurTeamComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_OurTeamComponent,data:{}});
export function View_OurTeamComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,([] as any[]),(null as any),(null as any));
}
export function View_OurTeamComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-our-team',
      ([] as any[]),(null as any),(null as any),(null as any),View_OurTeamComponent_0,
      RenderType_OurTeamComponent)),i1.ɵdid(114688,(null as any),0,i2.OurTeamComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const OurTeamComponentNgFactory:i1.ComponentFactory<i2.OurTeamComponent> = i1.ɵccf('app-our-team',
    i2.OurTeamComponent,View_OurTeamComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovbXRiL3NyYy9hcHAvaG9tZS9vdXItdGVhbS9vdXItdGVhbS5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRjovbXRiL3NyYy9hcHAvaG9tZS9vdXItdGVhbS9vdXItdGVhbS5jb21wb25lbnQudHMiLCJuZzovLy9GOi9tdGIvc3JjL2FwcC9ob21lL291ci10ZWFtL291ci10ZWFtLmNvbXBvbmVudC50cy5PdXJUZWFtQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGFwcC1vdXItdGVhbT48L2FwcC1vdXItdGVhbT4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQTtpQ0FBQSxVQUFBO01BQUE7SUFBQTs7OzsifQ==
