/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './profile-cards.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../../../../src/app/profile-cards/profile-cards.component';
const styles_ProfileCardsComponent:any[] = [i0.styles];
export const RenderType_ProfileCardsComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_ProfileCardsComponent,data:{}});
export function View_ProfileCardsComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵted((null as any),['\n\n\n'])),(_l()(),i1.ɵeld(0,(null as any),
      (null as any),31,'div',[['class','card']],(null as any),(null as any),(null as any),
      (null as any),(null as any))),(_l()(),i1.ɵted((null as any),['\n  '])),(_l()(),
      i1.ɵeld(0,(null as any),(null as any),0,'img',[['alt','John'],['src','img.jpg'],
          ['style','width:100%']],(null as any),(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i1.ɵted((null as any),['\n  '])),(_l()(),i1.ɵeld(0,
      (null as any),(null as any),26,'div',[['class','container']],(null as any),(null as any),
      (null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),['\n    '])),
      (_l()(),i1.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),
          ['John Doe'])),(_l()(),i1.ɵted((null as any),['\n    '])),(_l()(),i1.ɵeld(0,
          (null as any),(null as any),1,'p',[['class','title']],(null as any),(null as any),
          (null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),
          ['CEO & Founder, Example'])),(_l()(),i1.ɵted((null as any),['\n    '])),
      (_l()(),i1.ɵeld(0,(null as any),(null as any),1,'p',([] as any[]),(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),
          ['Harvard University'])),(_l()(),i1.ɵted((null as any),['\n    '])),(_l()(),
          i1.ɵeld(0,(null as any),(null as any),1,'a',[['href','#']],(null as any),
              (null as any),(null as any),(null as any),(null as any))),(_l()(),i1.ɵeld(0,
          (null as any),(null as any),0,'i',[['class','fa fa-dribbble']],(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),
          ['\n    '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'a',[['href',
          '#']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵeld(0,(null as any),(null as any),0,'i',[['class','fa fa-twitter']],
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted((null as any),['\n    '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),
          1,'a',[['href','#']],(null as any),(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i1.ɵeld(0,(null as any),(null as any),0,'i',[['class',
          'fa fa-linkedin']],(null as any),(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i1.ɵted((null as any),['\n    '])),(_l()(),i1.ɵeld(0,
          (null as any),(null as any),1,'a',[['href','#']],(null as any),(null as any),
          (null as any),(null as any),(null as any))),(_l()(),i1.ɵeld(0,(null as any),
          (null as any),0,'i',[['class','fa fa-facebook']],(null as any),(null as any),
          (null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),
          ['\n    '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),2,'p',([] as any[]),
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵeld(0,(null as any),(null as any),1,'button',([] as any[]),(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),
          ['Contact'])),(_l()(),i1.ɵted((null as any),['\n  '])),(_l()(),i1.ɵted((null as any),
          ['\n'])),(_l()(),i1.ɵted((null as any),['\n']))],(null as any),(null as any));
}
export function View_ProfileCardsComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-profile-cards',
      ([] as any[]),(null as any),(null as any),(null as any),View_ProfileCardsComponent_0,
      RenderType_ProfileCardsComponent)),i1.ɵdid(114688,(null as any),0,i2.ProfileCardsComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const ProfileCardsComponentNgFactory:i1.ComponentFactory<i2.ProfileCardsComponent> = i1.ɵccf('app-profile-cards',
    i2.ProfileCardsComponent,View_ProfileCardsComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovbXRiL3NyYy9hcHAvcHJvZmlsZS1jYXJkcy9wcm9maWxlLWNhcmRzLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9GOi9tdGIvc3JjL2FwcC9wcm9maWxlLWNhcmRzL3Byb2ZpbGUtY2FyZHMuY29tcG9uZW50LnRzIiwibmc6Ly8vRjovbXRiL3NyYy9hcHAvcHJvZmlsZS1jYXJkcy9wcm9maWxlLWNhcmRzLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRjovbXRiL3NyYy9hcHAvcHJvZmlsZS1jYXJkcy9wcm9maWxlLWNhcmRzLmNvbXBvbmVudC50cy5Qcm9maWxlQ2FyZHNDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCJcclxuXHJcblxyXG48ZGl2IGNsYXNzPVwiY2FyZFwiPlxyXG4gIDxpbWcgc3JjPVwiaW1nLmpwZ1wiIGFsdD1cIkpvaG5cIiBzdHlsZT1cIndpZHRoOjEwMCVcIj5cclxuICA8ZGl2IGNsYXNzPVwiY29udGFpbmVyXCI+XHJcbiAgICA8aDE+Sm9obiBEb2U8L2gxPlxyXG4gICAgPHAgY2xhc3M9XCJ0aXRsZVwiPkNFTyAmIEZvdW5kZXIsIEV4YW1wbGU8L3A+XHJcbiAgICA8cD5IYXJ2YXJkIFVuaXZlcnNpdHk8L3A+XHJcbiAgICA8YSBocmVmPVwiI1wiPjxpIGNsYXNzPVwiZmEgZmEtZHJpYmJibGVcIj48L2k+PC9hPlxyXG4gICAgPGEgaHJlZj1cIiNcIj48aSBjbGFzcz1cImZhIGZhLXR3aXR0ZXJcIj48L2k+PC9hPlxyXG4gICAgPGEgaHJlZj1cIiNcIj48aSBjbGFzcz1cImZhIGZhLWxpbmtlZGluXCI+PC9pPjwvYT5cclxuICAgIDxhIGhyZWY9XCIjXCI+PGkgY2xhc3M9XCJmYSBmYS1mYWNlYm9va1wiPjwvaT48L2E+XHJcbiAgICA8cD48YnV0dG9uPkNvbnRhY3Q8L2J1dHRvbj48L3A+XHJcbiAgPC9kaXY+XHJcbjwvZGl2PlxyXG4iLCI8YXBwLXByb2ZpbGUtY2FyZHM+PC9hcHAtcHJvZmlsZS1jYXJkcz4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7b0JDQUEsMkNBR0E7TUFBQTtNQUFBLDhCQUFrQix5Q0FDaEI7YUFBQTtVQUFBO1VBQUEsZ0JBQWlELHlDQUNqRDtNQUFBO01BQUEsNENBQXVCO01BQ3JCO1VBQUEsMERBQUk7VUFBQSxlQUFhLDJDQUNqQjtVQUFBO1VBQUEsNENBQWlCO1VBQUEsNkJBQTBCO01BQzNDO1VBQUEsMERBQUc7VUFBQSx5QkFBc0IsMkNBQ3pCO2lCQUFBO2NBQUEsMERBQVk7VUFBQTtVQUFBLDBEQUFrQztVQUFBLGFBQzlDO1VBQUE7TUFBWTtVQUFBO01BQWlDLDJDQUM3QztVQUFBO1VBQUEsZ0JBQVk7VUFBQTtVQUFBLGdCQUFrQywyQ0FDOUM7VUFBQTtVQUFBLDRDQUFZO1VBQUE7VUFBQSw0Q0FBa0M7VUFBQSxhQUM5QztVQUFBO01BQUc7VUFBQSwwREFBUTtVQUFBLGNBQW9CLHlDQUMzQjtVQUFBLFNBQ0Y7OztvQkNmTjtNQUFBO3NDQUFBLFVBQUE7TUFBQTtJQUFBOzs7OyJ9
