/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['#drawer[_ngcontent-%COMP%]   ul[_ngcontent-%COMP%]   li[_ngcontent-%COMP%]{\r\n\r\n    border: 1px solid white;\r\n\r\n    border-radius:3px;\r\n    padding: 5px;\r\n    margin:5px;\r\n    text-align: center;\r\n\r\n    box-shadow: 2px 1px 1px #888888;\r\n    transition: .3s transform;\r\n    transform: translateZ(0);\r\n    border-radius: 10px;\r\n}\r\n\r\n\r\n#drawer[_ngcontent-%COMP%]   ul[_ngcontent-%COMP%]   li[_ngcontent-%COMP%]   a[_ngcontent-%COMP%]{\r\n\r\n    color:#FFFFFF;\r\n}\r\n\r\n#drawer-toggle-label[_ngcontent-%COMP%]{\r\n    text-align: center;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovbXRiL3NyYy9hcHAvaGVhZGVyL2hlYWRlci5jb21wb25lbnQuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Y6L210Yi9zcmMvYXBwL2hlYWRlci9oZWFkZXIuY29tcG9uZW50LmNzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
