/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../src/app/app.module';
import * as i2 from '../../../src/app/app.component';
import * as i3 from './home/home.component.ngfactory';
import * as i4 from './stages/stages.component.ngfactory';
import * as i5 from './contact-us/contact-us.component.ngfactory';
import * as i6 from './rules-and-regulations/rules-and-regulations.component.ngfactory';
import * as i7 from './rider-registration/rider-registration.component.ngfactory';
import * as i8 from './volunteer-program/volunteer-program.component.ngfactory';
import * as i9 from './about-race/about-race.component.ngfactory';
import * as i10 from './gallery/gallery.component.ngfactory';
import * as i11 from './chat-to-register/chat-to-register.component.ngfactory';
import * as i12 from './app.component.ngfactory';
import * as i13 from '@angular/common';
import * as i14 from '@angular/platform-browser';
import * as i15 from '@angular/forms';
import * as i16 from '@angular/http';
import * as i17 from '@angular/router';
import * as i18 from '../../../src/app/app.services';
import * as i19 from '../../../src/app/home/home.component';
import * as i20 from '../../../src/app/stages/stages.component';
import * as i21 from '../../../src/app/contact-us/contact-us.component';
import * as i22 from '../../../src/app/rules-and-regulations/rules-and-regulations.component';
import * as i23 from '../../../src/app/rider-registration/rider-registration.component';
import * as i24 from '../../../src/app/volunteer-program/volunteer-program.component';
import * as i25 from '../../../src/app/about-race/about-race.component';
import * as i26 from '../../../src/app/gallery/gallery.component';
import * as i27 from '../../../src/app/chat-to-register/chat-to-register.component';
export const AppModuleNgFactory:i0.NgModuleFactory<i1.AppModule> = i0.ɵcmf(i1.AppModule,
    [i2.AppComponent],(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i3.HomeComponentNgFactory,i4.StagesComponentNgFactory,i5.ContactUsComponentNgFactory,
              i6.RulesAndRegulationsComponentNgFactory,i7.RiderRegistrationComponentNgFactory,
              i8.VolunteerProgramComponentNgFactory,i9.AboutRaceComponentNgFactory,
              i10.GalleryComponentNgFactory,i11.ChatToRegisterComponentNgFactory,i12.AppComponentNgFactory]],
              [3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(5120,i0.LOCALE_ID,
          i0.ɵm,[[3,i0.LOCALE_ID]]),i0.ɵmpd(4608,i13.NgLocalization,i13.NgLocaleLocalization,
          [i0.LOCALE_ID]),i0.ɵmpd(5120,i0.APP_ID,i0.ɵf,([] as any[])),i0.ɵmpd(5120,
          i0.IterableDiffers,i0.ɵk,([] as any[])),i0.ɵmpd(5120,i0.KeyValueDiffers,
          i0.ɵl,([] as any[])),i0.ɵmpd(4608,i14.DomSanitizer,i14.ɵe,[i14.DOCUMENT]),
          i0.ɵmpd(6144,i0.Sanitizer,(null as any),[i14.DomSanitizer]),i0.ɵmpd(4608,
              i14.HAMMER_GESTURE_CONFIG,i14.HammerGestureConfig,([] as any[])),i0.ɵmpd(5120,
              i14.EVENT_MANAGER_PLUGINS,(p0_0:any,p1_0:any,p2_0:any,p2_1:any) => {
                return [new i14.ɵDomEventsPlugin(p0_0),new i14.ɵKeyEventsPlugin(p1_0),
                    new i14.ɵHammerGesturesPlugin(p2_0,p2_1)];
              },[i14.DOCUMENT,i14.DOCUMENT,i14.DOCUMENT,i14.HAMMER_GESTURE_CONFIG]),
          i0.ɵmpd(4608,i14.EventManager,i14.EventManager,[i14.EVENT_MANAGER_PLUGINS,
              i0.NgZone]),i0.ɵmpd(135680,i14.ɵDomSharedStylesHost,i14.ɵDomSharedStylesHost,
              [i14.DOCUMENT]),i0.ɵmpd(4608,i14.ɵDomRendererFactory2,i14.ɵDomRendererFactory2,
              [i14.EventManager,i14.ɵDomSharedStylesHost]),i0.ɵmpd(6144,i0.RendererFactory2,
              (null as any),[i14.ɵDomRendererFactory2]),i0.ɵmpd(6144,i14.ɵSharedStylesHost,
              (null as any),[i14.ɵDomSharedStylesHost]),i0.ɵmpd(4608,i0.Testability,
              i0.Testability,[i0.NgZone]),i0.ɵmpd(4608,i14.Meta,i14.Meta,[i14.DOCUMENT]),
          i0.ɵmpd(4608,i14.Title,i14.Title,[i14.DOCUMENT]),i0.ɵmpd(4608,i15.ɵi,i15.ɵi,
              ([] as any[])),i0.ɵmpd(4608,i16.BrowserXhr,i16.BrowserXhr,([] as any[])),
          i0.ɵmpd(4608,i16.ResponseOptions,i16.BaseResponseOptions,([] as any[])),
          i0.ɵmpd(5120,i16.XSRFStrategy,i16.ɵb,([] as any[])),i0.ɵmpd(4608,i16.XHRBackend,
              i16.XHRBackend,[i16.BrowserXhr,i16.ResponseOptions,i16.XSRFStrategy]),
          i0.ɵmpd(4608,i16.RequestOptions,i16.BaseRequestOptions,([] as any[])),i0.ɵmpd(5120,
              i16.Http,i16.ɵc,[i16.XHRBackend,i16.RequestOptions]),i0.ɵmpd(5120,i17.ActivatedRoute,
              i17.ɵf,[i17.Router]),i0.ɵmpd(4608,i17.NoPreloading,i17.NoPreloading,
              ([] as any[])),i0.ɵmpd(6144,i17.PreloadingStrategy,(null as any),[i17.NoPreloading]),
          i0.ɵmpd(135680,i17.RouterPreloader,i17.RouterPreloader,[i17.Router,i0.NgModuleFactoryLoader,
              i0.Compiler,i0.Injector,i17.PreloadingStrategy]),i0.ɵmpd(4608,i17.PreloadAllModules,
              i17.PreloadAllModules,([] as any[])),i0.ɵmpd(5120,i17.ROUTER_INITIALIZER,
              i17.ɵi,[i17.ɵg]),i0.ɵmpd(5120,i0.APP_BOOTSTRAP_LISTENER,(p0_0:any) => {
            return [p0_0];
          },[i17.ROUTER_INITIALIZER]),i0.ɵmpd(4608,i18.MyServiceClass,i18.MyServiceClass,
              [i16.Http]),i0.ɵmpd(512,i13.CommonModule,i13.CommonModule,([] as any[])),
          i0.ɵmpd(1024,i0.ErrorHandler,i14.ɵa,([] as any[])),i0.ɵmpd(1024,i0.NgProbeToken,
              () => {
                return [i17.ɵb()];
              },([] as any[])),i0.ɵmpd(512,i17.ɵg,i17.ɵg,[i0.Injector]),i0.ɵmpd(1024,
              i0.APP_INITIALIZER,(p0_0:any,p0_1:any,p1_0:any) => {
                return [i14.ɵc(p0_0,p0_1),i17.ɵh(p1_0)];
              },[[2,i14.NgProbeToken],[2,i0.NgProbeToken],i17.ɵg]),i0.ɵmpd(512,i0.ApplicationInitStatus,
              i0.ApplicationInitStatus,[[2,i0.APP_INITIALIZER]]),i0.ɵmpd(131584,i0.ɵe,
              i0.ɵe,[i0.NgZone,i0.ɵConsole,i0.Injector,i0.ErrorHandler,i0.ComponentFactoryResolver,
                  i0.ApplicationInitStatus]),i0.ɵmpd(2048,i0.ApplicationRef,(null as any),
              [i0.ɵe]),i0.ɵmpd(512,i0.ApplicationModule,i0.ApplicationModule,[i0.ApplicationRef]),
          i0.ɵmpd(512,i14.BrowserModule,i14.BrowserModule,[[3,i14.BrowserModule]]),
          i0.ɵmpd(1024,i17.ɵa,i17.ɵd,[[3,i17.Router]]),i0.ɵmpd(512,i17.UrlSerializer,
              i17.DefaultUrlSerializer,([] as any[])),i0.ɵmpd(512,i17.ChildrenOutletContexts,
              i17.ChildrenOutletContexts,([] as any[])),i0.ɵmpd(256,i17.ROUTER_CONFIGURATION,
              {},([] as any[])),i0.ɵmpd(1024,i13.LocationStrategy,i17.ɵc,[i13.PlatformLocation,
              [2,i13.APP_BASE_HREF],i17.ROUTER_CONFIGURATION]),i0.ɵmpd(512,i13.Location,
              i13.Location,[i13.LocationStrategy]),i0.ɵmpd(512,i0.Compiler,i0.Compiler,
              ([] as any[])),i0.ɵmpd(512,i0.NgModuleFactoryLoader,i0.SystemJsNgModuleLoader,
              [i0.Compiler,[2,i0.SystemJsNgModuleLoaderConfig]]),i0.ɵmpd(1024,i17.ROUTES,
              () => {
                return [[{path:'',component:i19.HomeComponent,pathMatch:'full',data:{title:'Home Page',
                    metaDescription:'Testng home pag'}},{path:'home',component:i19.HomeComponent,
                    data:{title:'Home Page',metaDescription:'Testng home page'}},{path:'stages',
                    component:i20.StagesComponent},{path:'contact',component:i21.ContactUsComponent},
                    {path:'rules',component:i22.RulesAndRegulationsComponent},{path:'register/:email',
                        component:i23.RiderRegistrationComponent},{path:'volunteer',
                        component:i24.VolunteerProgramComponent},{path:'race',component:i25.AboutRaceComponent,
                        data:{title:'About Race'}},{path:'gallery',component:i26.GalleryComponent},
                    {path:'chat',component:i27.ChatToRegisterComponent}]];
              },([] as any[])),i0.ɵmpd(1024,i17.Router,i17.ɵe,[i0.ApplicationRef,i17.UrlSerializer,
              i17.ChildrenOutletContexts,i13.Location,i0.Injector,i0.NgModuleFactoryLoader,
              i0.Compiler,i17.ROUTES,i17.ROUTER_CONFIGURATION,[2,i17.UrlHandlingStrategy],
              [2,i17.RouteReuseStrategy]]),i0.ɵmpd(512,i17.RouterModule,i17.RouterModule,
              [[2,i17.ɵa],[2,i17.Router]]),i0.ɵmpd(512,i15.ɵba,i15.ɵba,([] as any[])),
          i0.ɵmpd(512,i15.FormsModule,i15.FormsModule,([] as any[])),i0.ɵmpd(512,i16.HttpModule,
              i16.HttpModule,([] as any[])),i0.ɵmpd(512,i1.AppModule,i1.AppModule,
              ([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovbXRiL3NyYy9hcHAvYXBwLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9GOi9tdGIvc3JjL2FwcC9hcHAubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
