/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './app.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './header/header.component.ngfactory';
import * as i3 from '../../../src/app/header/header.component';
import * as i4 from '@angular/router';
import * as i5 from './footer/footer.component.ngfactory';
import * as i6 from '../../../src/app/footer/footer.component';
import * as i7 from '../../../src/app/app.services';
import * as i8 from '../../../src/app/app.component';
import * as i9 from '@angular/platform-browser';
const styles_AppComponent:any[] = [i0.styles];
export const RenderType_AppComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,styles:styles_AppComponent,
    data:{}});
export function View_AppComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵted((null as any),['\n'])),(_l()(),i1.ɵeld(0,(null as any),
      (null as any),1,'app-header',([] as any[]),(null as any),(null as any),(null as any),
      i2.View_HeaderComponent_0,i2.RenderType_HeaderComponent)),i1.ɵdid(114688,(null as any),
      0,i3.HeaderComponent,([] as any[]),(null as any),(null as any)),(_l()(),i1.ɵted((null as any),
      ['\n\n'])),(_l()(),i1.ɵeld(16777216,(null as any),(null as any),1,'router-outlet',
      ([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
      i1.ɵdid(212992,(null as any),0,i4.RouterOutlet,[i4.ChildrenOutletContexts,i1.ViewContainerRef,
          i1.ComponentFactoryResolver,[8,(null as any)],i1.ChangeDetectorRef],(null as any),
          (null as any)),(_l()(),i1.ɵted((null as any),['\n\n'])),(_l()(),i1.ɵeld(0,
          (null as any),(null as any),1,'app-footer',([] as any[]),(null as any),(null as any),
          (null as any),i5.View_FooterComponent_0,i5.RenderType_FooterComponent)),
      i1.ɵdid(114688,(null as any),0,i6.FooterComponent,[i7.MyServiceClass],(null as any),
          (null as any)),(_l()(),i1.ɵted((null as any),['\n']))],(_ck,_v) => {
    _ck(_v,2,0);
    _ck(_v,5,0);
    _ck(_v,8,0);
  },(null as any));
}
export function View_AppComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-root',([] as any[]),
      (null as any),(null as any),(null as any),View_AppComponent_0,RenderType_AppComponent)),
      i1.ɵdid(114688,(null as any),0,i8.AppComponent,[i4.Router,i9.Title,i4.ActivatedRoute,
          i9.Meta],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const AppComponentNgFactory:i1.ComponentFactory<i8.AppComponent> = i1.ɵccf('app-root',
    i8.AppComponent,View_AppComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovbXRiL3NyYy9hcHAvYXBwLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9GOi9tdGIvc3JjL2FwcC9hcHAuY29tcG9uZW50LnRzIiwibmc6Ly8vRjovbXRiL3NyYy9hcHAvYXBwLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRjovbXRiL3NyYy9hcHAvYXBwLmNvbXBvbmVudC50cy5BcHBDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCJcclxuPGFwcC1oZWFkZXI+PC9hcHAtaGVhZGVyPlxyXG5cclxuPHJvdXRlci1vdXRsZXQ+PC9yb3V0ZXItb3V0bGV0PlxyXG5cclxuPGFwcC1mb290ZXI+PC9hcHAtZm9vdGVyPlxyXG4iLCI8YXBwLXJvb3Q+PC9hcHAtcm9vdD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBLHVDQUNBO01BQUE7NkRBQUEsVUFBQTtNQUFBLGdFQUF5QjtNQUFBLFdBRXpCO01BQUE7YUFBQTtzQ0FBQTtVQUFBLGVBQStCLHlDQUUvQjtVQUFBO1VBQUE7YUFBQTtVQUFBLGVBQXlCO0lBSnpCO0lBRUE7SUFFQTs7OztvQkNMQTtNQUFBO2FBQUE7aUJBQUE7SUFBQTs7OzsifQ==
