/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['#boxup[_ngcontent-%COMP%]{\r\n    border: 2px solid black;\r\n    box-shadow: 4px 2px 2px #888888;\r\n    margin-bottom: 25px;\r\n    min-height: 400px;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovbXRiL3NyYy9hcHAvdm9sdW50ZWVyLXByb2dyYW0vdm9sdW50ZWVyLXByb2dyYW0uY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9GOi9tdGIvc3JjL2FwcC92b2x1bnRlZXItcHJvZ3JhbS92b2x1bnRlZXItcHJvZ3JhbS5jb21wb25lbnQuY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
