/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['ul[_ngcontent-%COMP%] {\r\n  list-style: none;\r\n  padding: 0.5em;\r\n}\r\nli[_ngcontent-%COMP%] {\r\n  padding-left: 1.3em;\r\n  padding-bottom: 0.5em;\r\n}\r\n\r\nh3[_ngcontent-%COMP%]{\r\n    font-weight: bold;\r\n}\r\n\r\nspan[_ngcontent-%COMP%] {\r\n    text-decoration: underline;\r\n}\r\n\r\n.heading_rulesnregulations[_ngcontent-%COMP%]   h1[_ngcontent-%COMP%]{\r\n    text-align: center;\r\n    padding-top: -0.5em;\r\n    font-weight: bold;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovbXRiL3NyYy9hcHAvcnVsZXMtYW5kLXJlZ3VsYXRpb25zL3J1bGVzLWFuZC1yZWd1bGF0aW9ucy5jb21wb25lbnQuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Y6L210Yi9zcmMvYXBwL3J1bGVzLWFuZC1yZWd1bGF0aW9ucy9ydWxlcy1hbmQtcmVndWxhdGlvbnMuY29tcG9uZW50LmNzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
